#ifndef YOUSEI_IZUMI_TATE_ROOM_0_H
#define YOUSEI_IZUMI_TATE_ROOM_0_H 1

extern SceneCmd yousei_izumi_tate_room_0Commands[];
extern s16 yousei_izumi_tate_room_0ObjectList_000040[];
extern ActorEntry yousei_izumi_tate_room_0ActorEntry_000048[];
extern RoomShapeCullable yousei_izumi_tate_room_0RoomShapeCullable_000060;
extern RoomShapeCullableEntry yousei_izumi_tate_room_0RoomShapeCullableEntry_00006C[1];
extern s32 yousei_izumi_tate_room_0_terminatorMaybe_00007C;
extern Vtx yousei_izumi_tate_room_0Vtx_000080[];
extern Gfx yousei_izumi_tate_room_0DL_002C10[];
extern Vtx yousei_izumi_tate_room_0Vtx_0039A0[];
extern Gfx yousei_izumi_tate_room_0DL_003FB0[];
#endif
