#ifndef HAIRAL_NIWA2_SCENE_H
#define HAIRAL_NIWA2_SCENE_H 1

extern SceneCmd hairal_niwa2_sceneCommands[];
extern ActorEntry hairal_niwa2_sceneStartPositionList0x000040[];
extern RomFile hairal_niwa2_sceneRoomList0x000050[];
extern Spawn hairal_niwa2_sceneEntranceList0x000058[];
extern EnvLightSettings hairal_niwa2_sceneLightSettings0x00005C[];
extern BgCamInfo hairal_niwa2_sceneCollisionHeader_002CD8CamDataList[];
extern SurfaceType hairal_niwa2_sceneCollisionHeader_002CD8SurfaceType[];
extern CollisionPoly hairal_niwa2_sceneCollisionHeader_002CD8Polygons[];
extern Vec3s hairal_niwa2_sceneCollisionHeader_002CD8Vertices[];
extern CollisionHeader hairal_niwa2_sceneCollisionHeader_002CD8;
#endif
